plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/anthonyboyd/Library/Application Support/Claude/silverpathnetwork"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]